version: '3.1'

services:
  app:
    container_name: prueba-app
    image: mmarnun/prueba:latest
    restart: always
    environment:
      DB_HOST: prueba-db
      DB_NAME: alexprueba
      DB_USER: alexprueba
      DB_PASSWORD: alexprueba
    ports:
      - 8081:80
    depends_on:
      - db

  db:
    container_name: prueba-db
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: alexprueba
      MYSQL_PASSWORD: alexprueba
      MYSQL_DATABASE: alexprueba
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
  mariadb_data:
